# Generated by Django 5.0.6 on 2024-08-10 20:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Guest',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('description', models.TextField()),
                ('designation', models.TextField()),
                ('image', models.ImageField(upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='Podcast',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('series', models.CharField(choices=[('Startup Podcast', 'Startup Podcast'), ('Entrepreneurial Echoes by onRec', 'Entrepreneurial Echoes by onRec'), ('Class of 2020s', 'Class of 2020s'), ('Career podcast', 'Career podcast')], max_length=50)),
                ('title', models.CharField(max_length=50)),
                ('release_date', models.DateField()),
                ('description', models.TextField()),
                ('spotify_link', models.URLField()),
                ('youtube_link', models.URLField()),
                ('thumbnail', models.ImageField(default='onrec logo.jpg', upload_to='static/api')),
                ('guest', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.guest')),
            ],
        ),
    ]
