# Generated by Django 5.0.6 on 2024-07-05 18:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='podcast',
            old_name='date_uploaded',
            new_name='date',
        ),
        migrations.RenameField(
            model_name='podcast',
            old_name='podcast_series',
            new_name='series',
        ),
        migrations.RenameField(
            model_name='podcast',
            old_name='podcast_title',
            new_name='title',
        ),
    ]
