# Generated by Django 5.0.6 on 2024-07-09 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_guest_podcast_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='podcast',
            name='thumbnail',
            field=models.ImageField(default='onRec/onRec/static/api/onrec logo.jpg', upload_to='static/api'),
        ),
    ]
