# Generated by Django 5.0.6 on 2024-09-02 08:55

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_podcast_release_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='podcast',
            name='series',
            field=models.CharField(choices=[('startup', 'startup'), ('Entrepreneurial', 'Entrepreneurial'), ('Classof', 'Classof'), ('career', 'career'), ('offbeat', 'offbeat'), ('wellness', 'wellness')], max_length=50),
        ),
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=100)),
                ('content', models.TextField()),
                ('release_date', models.DateField(default=django.utils.timezone.now)),
                ('medium_link', models.URLField()),
                ('podcast', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blogs', to='api.podcast')),
            ],
        ),
    ]
