# Generated by Django 5.1.4 on 2024-12-22 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_podcast_series_blog'),
    ]

    operations = [
        migrations.AddField(
            model_name='guest',
            name='social_link',
            field=models.URLField(default='https://www.instagram.com/iitr_onrec/'),
        ),
    ]
