# Generated by Django 5.0.6 on 2024-07-21 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_podcast_thumbnail'),
    ]

    operations = [
        migrations.AddField(
            model_name='guest',
            name='designation',
            field=models.TextField(default='onrec guest', max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='guest',
            name='image',
            field=models.ImageField(default='null', upload_to=''),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='podcast',
            name='thumbnail',
            field=models.ImageField(default='onrec logo.jpg', upload_to='static/api'),
        ),
    ]
