# Generated by Django 5.1.4 on 2024-12-22 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_podcast_poster'),
    ]

    operations = [
        migrations.AlterField(
            model_name='podcast',
            name='title',
            field=models.CharField(max_length=100),
        ),
    ]
